### ISSUE TITLE
Crash in demo app if secondary brush first selected from color tool than from palette

### ISSUE THREAD

**Issue by Mrxx99** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1320]
If you first select a secondary brush from the color tool in the demo application and then go to the pallete and click any item, an InvalidOperationException in "PaletteHelper.cs" is raised which closes the application.

Reproduction steps:
1. Open Demo app
2. Go to Color Tool
3. Select different color for Secondary
4. Go to Palette
5. Select any primary or accent color

![grafik](https://user-images.githubusercontent.com/33566379/61157756-59ae8e00-a4f7-11e9-9f9f-0c1ac042d94b.png)

Exception details:
```
System.InvalidOperationException
  HResult=0x80131509
  Message=SecondaryAccentBrush is not from standard swatches
  Source=MaterialDesignThemes.Wpf
  StackTrace:
   at MaterialDesignThemes.Wpf.PaletteHelper.QueryPalette() in D:\Alex\Bearbeitung\MySoftwareProjects\Other\MaterialDesign Toolkit\MaterialDesignInXamlToolkit\MaterialDesignThemes.Wpf\PaletteHelper.cs:line 134
   at MaterialDesignThemes.Wpf.PaletteHelper.ReplacePrimaryColor(Swatch swatch) in D:\Alex\Bearbeitung\MySoftwareProjects\Other\MaterialDesign Toolkit\MaterialDesignInXamlToolkit\MaterialDesignThemes.Wpf\PaletteHelper.cs:line 60
   at MaterialDesignColors.WpfExample.PaletteSelectorViewModel.ApplyPrimary(Swatch swatch) in D:\Alex\Bearbeitung\MySoftwareProjects\Other\MaterialDesign Toolkit\MaterialDesignInXamlToolkit\MainDemo.Wpf\PaletteSelectorViewModel.cs:line 28
   at MaterialDesignColors.WpfExample.PaletteSelectorViewModel.<>c.<.ctor>b__0_1(Object o) in D:\Alex\Bearbeitung\MySoftwareProjects\Other\MaterialDesign Toolkit\MaterialDesignInXamlToolkit\MainDemo.Wpf\PaletteSelectorViewModel.cs:line 24
   at MaterialDesignColors.WpfExample.Domain.AnotherCommandImplementation.Execute(Object parameter) in D:\Alex\Bearbeitung\MySoftwareProjects\Other\MaterialDesign Toolkit\MaterialDesignInXamlToolkit\MainDemo.Wpf\Domain\AnotherCommandImplementation.cs:line 33
   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.UIElement.OnMouseLeftButtonUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs args, Boolean trusted)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at System.Windows.Application.Run()
   at MaterialDesignColors.WpfExample.App.Main()


```

**Comment by Keboo** [comment]
This is a known issue in the demo app. With the new 2.6.0 theme APIs you must either switch over all of your calls, or stick to only using the old APIs.

With that said the demo app should be updated to use only the new theme APIs.
