### ISSUE TITLE
DataGridAssist throws System.InvalidOperationException when clicking on a DataGridTemplateColumn.HeaderTemplate with Run inside a TextBlock

### ISSUE THREAD

**Issue by LoRdPMN** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2134]
When using a HeaderTemplate like this:

```
<DataGridTemplateColumn.HeaderTemplate>
    <DataTemplate>
        <TextBlock TextAlignment="Center">
            Actual
            <LineBreak/>
            Amount
        </TextBlock>
    </DataTemplate>
</DataGridTemplateColumn.HeaderTemplate>
```

and clicking the ColumnHeader to reorder the DataGrid, if the pixel clicked is exactly above the rendered text, it throws a System.InvalidOperationException on a call from DataGridAssist to VisualTreeHelper.GetParent(), saying that "Run" is not a Visual.

I tracked down the issue to this commit: #1927 

In this part of DataGridAssist.cs:
```
var dataGridCell = originalSource
    .GetVisualAncestry()
    .OfType<DataGridCell>()
    .FirstOrDefault();
```
I think that `MaterialDesignThemes.Wpf.Extensions.GetVisualAncestry(DependencyObject leaf)` should be aware of stumbling into a Run object and try to use GetParent() on its parent instead of itself, but I am afraid of messing up with something else in code as it is used in other places and I am not so familiar with the library internals, so would be really nice if someone could shed some light.

Here is the stack trace:

```
System.InvalidOperationException: 'System.Windows.Documents.Run' is not a Visual or Visual3D.
   at MS.Internal.Media.VisualTreeUtils.AsVisual(DependencyObject element, Visual& visual, Visual3D& visual3D)
   at System.Windows.Media.VisualTreeHelper.GetParent(DependencyObject reference)
   at MaterialDesignThemes.Wpf.Extensions.GetVisualAncestry(DependencyObject leaf)+MoveNext()
   at System.Linq.Enumerable.OfTypeIterator[TResult](IEnumerable source)+MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
   at MaterialDesignThemes.Wpf.DataGridAssist.AllowDirectEditWithoutFocus(Object sender, MouseButtonEventArgs mouseArgs)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.ContentElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run()
```

**Comment by LoRdPMN** [comment]
Current workaround is to set the attached property `md:DataGridAssist.EnableEditBoxAssist` to `False`.

**Comment by Keboo** [comment]
That looks like a bug to me.
I think you are on the right path with the proposed solution. I would suggest a few things:

- [ ] `GetVisualAncestry` should validate that `leaf` is a `Visual` or `Visual3D` before passing it off to `VisualTreeHelper.GetParent`, blindly doing it is clearly problematic.
- [ ] If the above type check fails, I think it is acceptable to fall back to using `LogicalTreeHelper.GetParent`

We have started adding tests to this project so extra points for adding tests as well (either UI or unit tests; whichever is easier).
