### ISSUE TITLE
Broken binding errors after clicking on DataGrid header

### ISSUE THREAD

**Issue by TysonMN** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2196]
Under a particular set of circumstances involving Material Design in XAML, clicking the header of a `DataGrid` causes WPF to log nine warnings to `PresentationTraceSources.DataBindingSource`.

As far as I can tell, each of the following is necessary (i.e. this is a minimal working reproduction).
1. A `ResourceDictionary` containing the lines for colors and themes of Material Design in XAML as given in the [Super Quick Start](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/wiki/Super-Quick-Start).
2. A XAML file that defines the `DataGrid` and also adds that `ResourceDictionary` to the `Resources` of its top-level `FrameworkElement`.
~3. The entry point of the application is a `static Main` method.~
~4. That entry point instantiates the singleton `Application` and sets its `Resources` to those in the `ResourceDictionary` mentioned above.~
3. `Application` sets its `Resources` to those in the `ResourceDictionary` mentioned above.

Code is available in [this repo](https://github.com/TysonMN/MaterialDesignInXaml_DataGrid_reproduction) or in [this ZIP](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/files/5730778/WpfApp1.zip).

## Steps to reproduce
1. Run the application in Visual Studio
2. Open the Output window
3. Click the header of the `DataGrid`

## Expected behavior
Nothing appears in the Output window

## Actual behavior
WPF logs nine binding errors to `PresentationTraceSources.DataBindingSource`, which show up in the Output window.

![2020-12-19_15-47-15_435](https://user-images.githubusercontent.com/34664007/102700264-7e8d5180-4211-11eb-9f83-0e2755b3ec7e.gif)

```
System.Windows.Data Error: 4 : Cannot find source for binding with reference 'RelativeSource FindAncestor, AncestorType='System.Windows.Controls.DataGridRow', AncestorLevel='1''. BindingExpression:Path=Foreground; DataItem=null; target element is 'DataGridCell' (Name=''); target property is 'Foreground' (type 'Brush')
System.Windows.Data Error: 4 : Cannot find source for binding with reference 'RelativeSource FindAncestor, AncestorType='System.Windows.Controls.DataGrid', AncestorLevel='1''. BindingExpression:Path=HorizontalGridLinesBrush; DataItem=null; target element is 'DataGridRowHeader' (Name=''); target property is 'BorderBrush' (type 'Brush')
System.Windows.Data Error: 4 : Cannot find source for binding with reference 'RelativeSource FindAncestor, AncestorType='System.Windows.Controls.DataGrid', AncestorLevel='1''. BindingExpression:Path=GridLinesVisibility; DataItem=null; target element is 'DataGridRowHeader' (Name=''); target property is 'BorderThickness' (type 'Thickness')
System.Windows.Data Error: 4 : Cannot find source for binding with reference 'RelativeSource FindAncestor, AncestorType='System.Windows.Controls.DataGridRow', AncestorLevel='1''. BindingExpression:Path=Foreground; DataItem=null; target element is 'DataGridCell' (Name=''); target property is 'Foreground' (type 'Brush')
System.Windows.Data Error: 4 : Cannot find source for binding with reference 'RelativeSource FindAncestor, AncestorType='System.Windows.Controls.DataGrid', AncestorLevel='1''. BindingExpression:Path=HorizontalGridLinesBrush; DataItem=null; target element is 'DataGridRowHeader' (Name=''); target property is 'BorderBrush' (type 'Brush')
System.Windows.Data Error: 4 : Cannot find source for binding with reference 'RelativeSource FindAncestor, AncestorType='System.Windows.Controls.DataGrid', AncestorLevel='1''. BindingExpression:Path=GridLinesVisibility; DataItem=null; target element is 'DataGridRowHeader' (Name=''); target property is 'BorderThickness' (type 'Thickness')
System.Windows.Data Error: 4 : Cannot find source for binding with reference 'RelativeSource FindAncestor, AncestorType='System.Windows.Controls.DataGridRow', AncestorLevel='1''. BindingExpression:Path=Foreground; DataItem=null; target element is 'DataGridCell' (Name=''); target property is 'Foreground' (type 'Brush')
System.Windows.Data Error: 4 : Cannot find source for binding with reference 'RelativeSource FindAncestor, AncestorType='System.Windows.Controls.DataGrid', AncestorLevel='1''. BindingExpression:Path=HorizontalGridLinesBrush; DataItem=null; target element is 'DataGridRowHeader' (Name=''); target property is 'BorderBrush' (type 'Brush')
System.Windows.Data Error: 4 : Cannot find source for binding with reference 'RelativeSource FindAncestor, AncestorType='System.Windows.Controls.DataGrid', AncestorLevel='1''. BindingExpression:Path=GridLinesVisibility; DataItem=null; target element is 'DataGridRowHeader' (Name=''); target property is 'BorderThickness' (type 'Thickness')
```

**Comment by TysonMN** [comment]
The entry-point of my application is a `static Main` method (instead of through [`Applicaiton.StartupUri`](https://docs.microsoft.com/en-us/dotnet/api/system.windows.application.startupuri)) because I use [Elmish.WPF](https://github.com/elmish/Elmish.WPF).

My entry point instantiates the singleton `Application` and sets its `Resources` to those in that `ResourceDictionary` as a workaround to issue #2040 (which has been fixed but not yet appeared in a release).

I hope someone can give me a hint about why these binding errors are happening.  In the meantime, I plan to continue investigating.

Consider the following change to the code.  This is still a workaround to issue #2040 and achieves the expected behavior described above in the provided example code.  Unfortunately, that same change in my application at work still exhibits the actual behavior described above.  This means my "minimal working reproduction" isn't quite so minimal (yet).
> \-- app.Resources = new DefaultResourceDicitionaryContainer().Resources;
> \+ app.Resources = mainWindow.Resources;

**Comment by TysonMN** [comment]
The three paths among those errors are `Foreground`, `HorizontalGridLinesBrush`, and `GridLinesVisibility`.  The second two are rare enough that I can list all references.  All fives references to `HorizontalGridLinesBrush` and four references to `GridLinesVisibility` occur in these four code snippets.

https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/c36307b01f5a47f0b9cf1ede8adb4d7ca5546a34/MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.DataGrid.xaml#L187-L189

https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/c36307b01f5a47f0b9cf1ede8adb4d7ca5546a34/MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.DataGrid.xaml#L256-L262

https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/c36307b01f5a47f0b9cf1ede8adb4d7ca5546a34/MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.DataGrid.xaml#L337-L339

https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/c36307b01f5a47f0b9cf1ede8adb4d7ca5546a34/MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.DataGrid.xaml#L424-L439

**Comment by Xaalek** [comment]
Same, my application crashes when I click on the header. I have this issue when columns are autogenerated. If columns are not autogenerated, I don't have any problem

**Comment by TysonMN** [comment]
@Xaalek, can you share link to a repo or ZIP that reproduces the behavior you describe?

My application doesn't crash, so your issue might be a different problem (but I am still interested to see your reproduction).

**Comment by Xaalek** [comment]
@TysonMN I'm running my application without debugger (ctrl + F5), maybe you can try with your app and see what happens

**Comment by Xaalek** [comment]
System.Windows.Documents.Run is not a Visual or Visual 3D object
![image](https://user-images.githubusercontent.com/54487782/102896053-13888880-4466-11eb-8e3d-34b0aa004f19.png)

**Comment by Xaalek** [comment]
I don't know why but when I change the header of the columns it fixes the issue.

**Comment by TysonMN** [comment]
When executing the EXE in the `bin` directory, neither my MWE (linked above) or my application at work crash when clicking on the header of the `DataGrid`.

@Xaalek, if you provide _executable code_ that reproduces the behavior you describe, then I will look into your problem.  I don't know how to test only using the code snippets that you provided.

_However_, for both my MWE (after adding a popup on a binding error) and in my application at work, these binding errors do not occur when executing the EXE in the `bin` directory.  I am starting to think this is an issue with Visual Studio.  I will submit a bug report to them.

**Comment by Xaalek** [comment]
@TysonMN My code is in VB .Net and I'm using a DataBase to populate my datagrid. So it would be complicated to test it.

But here is my code is C#

SqlCommand cmd = new SqlCommand();
cmd.CommandText = "SELECT * FROM temp_rech_dossier_route";
cmd.Connection = connSQLServer;
SqlDataAdapter da = new SqlDataAdapter(cmd);
DataTable dt = new DataTable("RECH");
da.Fill(dt);
DataGridRech.ItemsSource = dt.DefaultView;

If you want to test it, you will have to put it in a event for exemple window load event. Moreover you will have to replace the `connSQLServer` by your sql connection, replace `DataGridRech` by the name of your datagrid and finally change the sql query.

**Comment by TysonMN** [comment]
I am not sure I could correctly do all that...but if you are willing to provide a [minimal working example](https://en.wikipedia.org/wiki/Minimal_working_example), then I will test it.

**Comment by TysonMN** [comment]
I created [this issue](https://developercommunity2.visualstudio.com/t/Binding-errors-when-running-in-Visual-St/1294226) on Visual Studio Developer Community about the different behavior when running through Visual Studio and vs directly running the EXE.

**Comment by TysonMN** [comment]
These are the five styles with `DataGrid` in their name.
https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/c36307b01f5a47f0b9cf1ede8adb4d7ca5546a34/MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.Defaults.xaml#L58-L62

If I comment out the first four and just leave `DataGridRowHeader`, then only the six binding errors for `HorizontalGridLinesBrush` and `GridLinesVisibility` occur.

**Comment by TysonMN** [comment]
> My entry point instantiates the singleton `Application` and sets its `Resources` to those in that `ResourceDictionary` as a workaround to issue #2040 (which has been fixed but not yet appeared in a release).
> 
> Consider the following change to the code. This is still a workaround to issue #2040 and achieves the expected behavior described above in the provided example code. Unfortunately, that same change in my application at work still exhibits the actual behavior described above. This means my "minimal working reproduction" isn't quite so minimal (or maybe it is too minimal).
> 
> > --- app.Resources = new DefaultResourceDicitionaryContainer().Resources;
> > ++ app.Resources = mainWindow.Resources;

I figured out a workaround for my case.  I just realized that Material Design in XAML publishes a (pre-release) NuGet package each time a pull request is completed.  I have updated to the latest pre-release, which includes a fix for #2040, and then used the quoted workaround (which, in my case, is to simply not set the `Resources` of `Application`).

I will no longer be actively investigating this issue, but I will follow up on any suggestions.

**Comment by LoRdPMN** [comment]
> System.Windows.Documents.Run is not a Visual or Visual 3D object
> ![image](https://user-images.githubusercontent.com/54487782/102896053-13888880-4466-11eb-8e3d-34b0aa004f19.png)
> 
> System.InvalidOperationException
> HResult=0x80131509
> Message='System.Windows.Documents.Run' n'est pas un objet Visual ou Visual3D.
> Source=PresentationCore
> StackTrace:
> at MS.Internal.Media.VisualTreeUtils.AsVisual(DependencyObject element, Visual& visual, Visual3D& visual3D)
> at MS.Internal.Media.VisualTreeUtils.AsNonNullVisual(DependencyObject element, Visual& visual, Visual3D& visual3D)
> at System.Windows.Media.VisualTreeHelper.GetParent(DependencyObject reference)
> at MaterialDesignThemes.Wpf.Extensions.d__3.MoveNext()
> at System.Linq.Enumerable.d__95`1.MoveNext() at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
> at MaterialDesignThemes.Wpf.DataGridAssist.AllowDirectEditWithoutFocus(Object sender, MouseButtonEventArgs mouseArgs)
> ...
> at TransitRoute.Application.Main()
> 
> This exception was originally thrown at this call stack:
> [External Code]

I reported steps to reproduce this issue here #2134, with possible solution but, unfortunately, I had no time to work on it. You can grab it if you want.

**Comment by TysonMN** [comment]
Both this issue and #2134 include clicking on the header of a `DataGrid` as a reproduction step.  Then they continue separately by describing different issues that result.  Do you think they have more in common?  For example, do you think they might have the same fix?

**Comment by LoRdPMN** [comment]
I don't think so... I have a lot of complex DataGrids, including ones with custom headers and none of them are causing binding warnings.
Did you tried my workaround on #2134?
I saw that you are using the 3.2.0 version, can you try to reproduce using the lastest pre-release version?

**Comment by LoRdPMN** [comment]
I figured out the cause of your issue on your repo 😃
You are merging "MyDictionary.xaml" both into your App.xaml and Window.xaml.
Merging it into App.xaml is enough for the whole application, so if you just remove

```
  <Window.Resources>
    <ResourceDictionary Source="MyDictionary.xaml"/>
  </Window.Resources>
```

it works as expected!

**Comment by TysonMN** [comment]
> I saw that you are using the 3.2.0 version, can you try to reproduce using the latest pre-release version?

Testing the latest prerelease is a good idea.  I didn't think of that.  I just tested version `4.0.0-ci2347`, but the bad behavior remains.

> Did you tried my workaround on #2134?

I just did, but the bad behavior remains.

> I figured out the cause of your issue on your repo 😃
> You are merging "MyDictionary.xaml" both into your App.xaml and Window.xaml.
> Merging it into App.xaml is enough for the whole application, so if you just remove
> 
> ```
>   <Window.Resources>
>     <ResourceDictionary Source="MyDictionary.xaml"/>
>   </Window.Resources>
> ```
> 
> it works as expected!

Sure.  As I stated in https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/issues/2196#issuecomment-749757926, I was able to avoid this bug by _not including_ `MyDictionary.xaml` in `App.xaml` and _including_ `MyDictionary.xaml` in `MainWindow.xaml`.

But what do you mean by "the cause"?  I agree that including `MyDictionary.xaml` in both `App.xaml` and `MainWindow.xaml` is necessary to reproduce the bad behavior.  In this content, I think of a "cause" as an explanation for the behavior.  Do you know why _in principle_ bad behavior would result from including the same `ResourceDictionary` in both `App.xaml` and some `Window`?  I don't know of any reason for this.

**Comment by LoRdPMN** [comment]
I can't tell exactly without digging deep into the library code, but probably it sets some animations bindings with relative source on the fly, so doing it twice probably is breaking it.
Also it is best to not create duplicate resource allocations by merging it again.

> Sure. As I stated in [#2196 (comment)](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/issues/2196#issuecomment-749757926), I was able to avoid this bug by _not including_ `MyDictionary.xaml` in `App.xaml` and _including_ `MyDictionary.xaml` in `MainWindow.xaml`.

Sorry I didn't see that, but anyways, I think the best is to merge it on App.xaml instead of each view, unless you need views without material design.

**Comment by TysonMN** [comment]
> Sorry I didn't see that

No problem.

> I can't tell exactly without digging deep into the library code, but probably it sets some animations bindings with relative source on the fly, so doing it twice probably is breaking it.

Interesting.  There is an arrow that rotates 180 degrees (to point up or down) when clicking on the header.  That is a lead for someone to investigate at some point.

> it is best to not create duplicate resource allocations by merging it again.
> ...
> I think the best is to merge it on App.xaml instead of each view, unless you need views without material design.

I don't typically have an `App.xaml` file since I use [Elmish.WPF](https://github.com/elmish/Elmish.WPF).  See, for example, the [`SimpleCounter` sample](https://github.com/elmish/Elmish.WPF/tree/master/src/Samples/SingleCounter.Views).

Maybe an Elmish.WPF application can also have a traditional `App.xaml` file.  I will investigate this.

**Comment by ThomasMader** [comment]
I am having the same problem but only when I collapse one of my columns.
It is initially collapsed. When I set it visible there are no problems. Only when I disable it I get two binding errors which is reproducable every time I collapse it again.

```
System.Windows.Data Error: 4 : Cannot find source for binding with reference 'RelativeSource FindAncestor, AncestorType='System.Windows.Controls.DataGrid', AncestorLevel='1''. BindingExpression:Path=HorizontalGridLinesBrush; DataItem=null; target element is 'DataGridColumnHeader' (Name=''); target property is 'BorderBrush' (type 'Brush')
System.Windows.Data Error: 4 : Cannot find source for binding with reference 'RelativeSource FindAncestor, AncestorType='System.Windows.Controls.DataGrid', AncestorLevel='1''. BindingExpression:Path=GridLinesVisibility; DataItem=null; target element is 'DataGridColumnHeader' (Name=''); target property is 'BorderThickness' (type 'Thickness')
```

```
                <DataGridTextColumn 
                    Header="Properties" 
                    Binding="{Binding Properties}" 
                    Visibility="{Binding Data.DisplayProperties,Source={StaticResource Proxy},Converter={StaticResource BooleanToVisibilityConverter}}"/>
```

It also happens if I change the Visibility of the column via code behind.

**Comment by TysonMN** [comment]
@ThomasMader, can share a MWE that exhibits that behavior?

**Comment by ThomasMader** [comment]
Here you go. [1]
I took your example and reworked it to reproduce my problem. The problem appears only when MaterialDesignDataGridCell is used as CellStyle and MaterialDesignDataGridColumnHeader as ColumnHeaderStyle.

[1] https://drive.google.com/file/d/1Hig3byFZltPY4gJKXiFZZ3tahFCNS3px/view?usp=sharing
