### ISSUE TITLE
OnSupportHorizontalScrollChanged method in MaterialDesignThemes.Wpf.ScrollViewerAssist class throws OverflowException

### ISSUE THREAD

**Issue by bilaxos** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2668]
I am developing a WPF application that uses MaterialDesignThemes. I noticed one issue and couldn't find any related question asked about it. 
I have Logitech MX Master 3 mouse and it has horizontal scroll wheel. When my app runs, if I scroll left on any place it won't be a problem. But if I scroll right even a little bit, my app crashes. 
My nuget package version is 4.5.0 by the way.

`System.OverflowException: Arithmetic operation resulted in an overflow.
   at System.IntPtr.ToInt32()
   at MaterialDesignThemes.Wpf.ScrollViewerAssist.<>c__DisplayClass18_1.<OnSupportHorizontalScrollChanged>g__Hook|6(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.PublicHooksFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run()
   at HMC.API.TheMonitoringTool.Presentation.App.Main()`

![image](https://user-images.githubusercontent.com/12683505/167030896-339ec1fd-121b-4859-8aba-472cffbf7260.png)

**Comment by Keboo** [comment]
Oops, that looks like a bug that is probably my fault. I suspect I know the answer, but if you are able I would love to know the value of `wParam` there.

**Comment by bilaxos** [comment]
> Oops, that looks like a bug that is probably my fault. I suspect I know the answer, but if you are able I would love to know the value of `wParam` there.

Couldn't do what you asked :/ 
I am getting AccessViolationException when run `Marshal.ReadIntPtr(wParam)` on Evaluate Expression tab. If you describe how to do it, I can help you.

**Comment by Keboo** [comment]
I think I found the issue. There will be a fix in tonight's nightly release.

**Comment by bilaxos** [comment]
> I think I found the issue. There will be a fix in tonight's nightly release.

Okey, waiting for release. Thank you for your quick reply.
