### ISSUE TITLE
Button static resource not resolving

### ISSUE THREAD

**Issue by sdpenner** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#3491]
### Bug explanation

I am trying to tweak a number of styles in my window.  All the styles changes work except for the button.  None of the existing button styles can be resolved at runtime.  They resolve OK during design time.

I'm new to this, so it may be something on my end, but I am confused how the other controls can be styled but the button is not working.

Any help would be greatly appreciated.

App:
```
            <ResourceDictionary.MergedDictionaries>
                <materialDesign:BundledTheme BaseTheme="Light" PrimaryColor="DeepPurple" SecondaryColor="Lime" />
                <ResourceDictionary Source="pack://application:,,,/MaterialDesignThemes.Wpf;component/Themes/MaterialDesign2.Defaults.xaml" />
            </ResourceDictionary.MergedDictionaries>
```

Window:
```
           <Style TargetType="{x:Type TextBox}" BasedOn="{StaticResource MaterialDesignTextBox}">
               <Setter Property="Margin" Value="0,0,5,0"/>
               <Setter Property="VerticalAlignment" Value="Center"/>
               <Setter Property="MinWidth" Value="150"/>
           </Style>
           <Style TargetType="{x:Type Button}" BasedOn="{StaticResource MaterialDesignRaisedButton}">
               <Setter Property="Margin" Value="0,0,10,0"/>
               <Setter Property="MinWidth" Value="100"/>
               <Setter Property="VerticalAlignment" Value="Center"/>
               <Setter Property="Padding" Value="2"/>
           </Style>
           <Style TargetType="{x:Type ComboBox}" BasedOn="{StaticResource MaterialDesignComboBox}">
               <Setter Property="Margin" Value="0,0,10,0"/>
               <Setter Property="MinWidth" Value="100"/>
               <Setter Property="VerticalAlignment" Value="Center"/>
           </Style>
           <Style TargetType="{x:Type Label}" BasedOn="{StaticResource MaterialDesignLabel}">
               <Setter Property="Margin" Value="0,0,5,0"/>
               <Setter Property="VerticalAlignment" Value="Center"/>
           </Style>
```
 
System.Windows.Markup.XamlParseException
  HResult=0x80131501
  Message='Provide value on 'System.Windows.Markup.StaticResourceHolder' threw an exception.' Line number '22' and line position '20'.
  Source=PresentationFramework
  StackTrace:
   at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
   at TLSRemoteControlUI.MainWindow.InitializeComponent() in D:\Code\repos\TLSRemoteControl\TLSRemoteControl\MainWindow.xaml:line 1

  This exception was originally thrown at this call stack:
    [External Code]

Inner Exception 1:
Exception: Cannot find resource named 'MaterialDesignRaisedButton'. Resource names are case sensitive.

### Version

5.0.0

**Comment by sdpenner** [comment]
Never mind.  I resolved this by adding a resource dictionary for each control to be styled into the window resources.  I thought that I could do this in the App.xaml, but that doesn't work.

For instance:
```
    <Window.Resources>
        <ResourceDictionary>
            <ResourceDictionary.MergedDictionaries>
                <ResourceDictionary Source="pack://application:,,,/MaterialDesignThemes.Wpf;component/Themes/MaterialDesignTheme.Button.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MaterialDesignThemes.Wpf;component/Themes/MaterialDesignTheme.CheckBox.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MaterialDesignThemes.Wpf;component/Themes/MaterialDesignTheme.ComboBox.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MaterialDesignThemes.Wpf;component/Themes/MaterialDesignTheme.ListBox.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MaterialDesignThemes.Wpf;component/Themes/MaterialDesignTheme.TextBox.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MaterialDesignThemes.Wpf;component/Themes/MaterialDesignTheme.RadioButton.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MaterialDesignThemes.Wpf;component/Themes/MaterialDesignTheme.SplitButton.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MaterialDesignThemes.Wpf;component/Themes/MaterialDesignTheme.TextBlock.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MaterialDesignThemes.Wpf;component/Themes/MaterialDesignTheme.Label.xaml" />
            </ResourceDictionary.MergedDictionaries>
            <BooleanToVisibilityConverter x:Key="BooleanToVisibilityConverter" />
        </ResourceDictionary>
    </Window.Resources>
```
