### ISSUE TITLE
MaterialDesignSwitchToggleButton:  'System.Windows.Media.Animation.DoubleAnimation' cannot use default origin value of 'NaN' on Window Exit

### ISSUE THREAD

**Issue by TWhidden** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#3740]
### Bug explanation

Moving to Material Design 3. Having a problem with `MaterialDesignSwitchToggleButton`.  The other ToggleButtons styles don't appear to have this exception. 

When closing the parent window after this style has been loaded, I get an exception. I am guessing the exit animation is causing this. Not sure if it's because there is no `from` value? 

https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/5df62fa8faa82b198320f764e6b0a7de4d2f49c7/src/MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.ToggleButton.xaml#L381

I am still researching this and have not created a side project to test this yet.  That will be next, but under pressure to finish this project, so will select a different style for the meantime.

Exception is crazy long, so will post the final part of it.

```
System.InvalidOperationException: 'System.Windows.Media.Animation.DoubleAnimation' cannot use default origin value of 'NaN'.
   at System.Windows.Media.Animation.DoubleAnimation.GetCurrentValueCore(Double defaultOriginValue, Double defaultDestinationValue, AnimationClock animationClock)
   at System.Windows.Media.Animation.DoubleAnimationBase.GetCurrentValue(Object defaultOriginValue, Object defaultDestinationValue, AnimationClock animationClock)
   at System.Windows.Media.Animation.AnimationStorage.GetCurrentPropertyValue(AnimationStorage storage, DependencyObject d, DependencyProperty dp, PropertyMetadata metadata, Object baseValue)
   at System.Windows.Media.Animation.AnimationStorage.EvaluateAnimatedValue(PropertyMetadata metadata, EffectiveValueEntry& entry)
   at System.Windows.UIElement.EvaluateAnimatedValueCore(DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry& entry)
```

More to come - but opening this up just in case there is something obvious I may be missing.

Xaml usage:
```xaml
<ToggleButton Style="{DynamicResource MaterialDesignSwitchToggleButton}"
              ToolTip="Something"
              IsChecked="{Binding SomeBoolBinding, Mode=TwoWay}"
              Margin="2" />
```

### Version

5.1.0

**Comment by corvinsz** [comment]
@TWhidden If I understand correctly, the reproduction steps should be:

1. Open a new Window containing XAML you provided (ToggleButton and the approriate style)
2. Closing the Window should raise an unhandled exception

I am unable to reproduce this problem using the Material Design 3 defaults:
![395200963-d962512c-f3f0-4149-bef0-15f0ced51ce8](https://github.com/user-attachments/assets/a08bd8b1-7ed5-4b1c-b8bb-8abc6e5c5794)

**Comment by TWhidden** [comment]
It appears there's an environmental issue in my setup. For the demo, I had to revert to a standard checkbox to bypass the problem, but I plan to investigate further soon.

Could you please zip up that quick test, drop a link? I’d like to apply the application-specific settings to see if I can reproduce the issue. I suspect it might be related to how I’m applying styles. Since I'm integrating it as a plugin within another application, I couldn't apply the styles to the global App resources without causing conflicts in the host application (poisoned their visuals tree with my styles and colors). Currently, the style is loaded as a merged dictionary and applied throughout the child visual tree, including the popup with the same resource applied at the window level.

Interestingly, other Material Design visuals function correctly, and the issue seems to be isolated to the ToggleButton at this time.

I'll have more time next week to poke at this, as I really like the MD3 ToggleButton styles. 

Thanks for looking into this!

**Comment by corvinsz** [comment]
Here you go: https://github.com/corvinsz/MDIX3740
I'm quite busy currently, so you are welcome to fiddle around yourself 😄

**Comment by corvinsz** [comment]
@TWhidden were you able to pinpoint the bug and find out if the problem lies on your side or on the libraries?

**Comment by TWhidden** [comment]
I keep running into it only for that specific style, sorry for the delay - it's been on my to-do list.  The other `ToggleButton` styles don't have it though, so been using those as a workaround.

**Comment by TWhidden** [comment]
Ok... have an easy reproduceable;  Placed the `ToggleButton` in a `ContentControl`; Change the `ContentControl.Content` to something else.

Slightly different than what I thought, nothing to do with the window state. 

Here is a Window:

```xaml
<Window x:Class="ToggleButtonIssueTest.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:materialDesign="http://materialdesigninxaml.net/winfx/xaml/themes"
        mc:Ignorable="d"
        Title="MainWindow"
        Height="450"
        Width="800">
  <Window.Resources>
    <ResourceDictionary>
      <ResourceDictionary.MergedDictionaries>
        <!-- Load the Material Design styles - Cant set globally due to being a Plugin and poisoning outside controls -->

        <ResourceDictionary Source="pack://application:,,,/MaterialDesignThemes.Wpf;component/Themes/MaterialDesignTheme.Dark.xaml" />
        <ResourceDictionary Source="pack://application:,,,/MaterialDesignThemes.Wpf;component/Themes/MaterialDesign3.Defaults.xaml" />
        <ResourceDictionary Source="pack://application:,,,/MaterialDesignColors;component/Themes/Recommended/Primary/MaterialDesignColor.DeepPurple.xaml" />
        <ResourceDictionary Source="pack://application:,,,/MaterialDesignColors;component/Themes/Recommended/Secondary/MaterialDesignColor.Lime.xaml" />

      </ResourceDictionary.MergedDictionaries>
    </ResourceDictionary>
  </Window.Resources>
  <Grid>
    <Grid.RowDefinitions>
      <RowDefinition />
      <RowDefinition />
    </Grid.RowDefinitions>

    <Button Content="ClickMe"
            Click="ButtonBase_OnClick" />

    <ContentControl x:Name="Test"
                    Grid.Row="1">
      <ToggleButton Style="{DynamicResource MaterialDesignSwitchToggleButton}"
                    ToolTip="MaterialDesignSwitchToggleButton with Content and ToggleButtonAssist.OnContent">
        <materialDesign:PackIcon Kind="Pin"
                                 RenderTransformOrigin=".5,.5">
          <materialDesign:PackIcon.RenderTransform>
            <RotateTransform Angle="45" />
          </materialDesign:PackIcon.RenderTransform>
        </materialDesign:PackIcon>
        <materialDesign:ToggleButtonAssist.OnContent>
          <materialDesign:PackIcon Kind="Pin" />
        </materialDesign:ToggleButtonAssist.OnContent>
      </ToggleButton>
    </ContentControl>

  </Grid>
</Window>

```

Here is the code behind

```xaml
namespace ToggleButtonIssueTest
{
    /// <summary>
    ///     Interaction logic for MainWindow.xaml
    /// </summary>
    public partial class MainWindow : Window
    {
        public MainWindow() => InitializeComponent();

        private void ButtonBase_OnClick(object sender, RoutedEventArgs e) => Test.Content = "test";
    }
}

```

![Image](https://github.com/user-attachments/assets/b2448e60-a4be-484a-80cb-914bb9c04da3)

**Comment by TWhidden** [comment]
> Here you go: https://github.com/corvinsz/MDIX3740 I'm quite busy currently, so you are welcome to fiddle around yourself 😄

*Side note* -- I had no idea that the `CommunityToolkit` had those codegen features. `[ObservableProperty]`  - Looks like some major refactoring in my future.  Learned something looking at your sample code.  Appreciate that!

**Comment by corvinsz** [comment]
@TWhidden the problem is that you are referencing the Style of the ToggleButton via `DynamicResource`. If you change it to `StaticResource` it works fine:
```xaml
...
    <ToggleButton Style="{StaticResource MaterialDesignSwitchToggleButton}">
...
```
As described in [this comment](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/issues/3718#issuecomment-2457686220) Styles are almost 99% of the time referenced via `StaticResource`.

And yes, the `CommunityToolkit.MVVM` is absolute brilliant to work with. It just sucks if you are still working with old(er) projects which are still on .NET Framework 4.x and you can't make use of the library  😭

**Comment by TWhidden** [comment]
I completely understand the rationale for using a `StaticResource`. Unfortunately, in our use case, it isn't feasible. Our controls are loaded before any resources are available, which results in an exception. As a result, I am limited to using `DynamicResource`.  

I can only use merged dictionaries in my user controls. I cannot load the style statically in the application because I don’t own the application (it's a plugin with no AppDomain isolation). If I try to set the application’s themes globally, it disrupts the parent process’s visuals. Therefore, I am restricted to using merged dictionaries within the visual tree’s children.   In my production use cases, the user controls and visuals are created before they're added to the visual tree. And I typically do not have the material UI themes on every control. The example I gave above was just showing the issue. 

The issue I’m encountering only arises with this specific example. Other Material Design styles, at least the ones we’re using, do not exhibit this behavior.  

While troubleshooting last night, I narrowed it down to an animation triggered when the visual is being removed. However, I haven’t yet identified a solution.  

I still believe supporting `DynamicResource` is worthwhile, even if there’s a performance cost associated with it.

**Comment by corvinsz** [comment]
> I can only use merged dictionaries in my user controls. I cannot load the style statically in the application because I don’t own the application (it's a plugin with no AppDomain isolation).

@TWhidden oh you are trying to use this library inside of a class library? Until your last comment, this wasn't clear to me.
Sorry if I have overlooked it in any of your comments.

From some quick testing I have found out that unfortunately the usual way of setting up the class library showcased [here](https://github.com/Keboo/MaterialDesignInXaml.Examples/tree/68b4feebf1cdca0f0229d3b7b184e8ea0a1cf3f0/Theming/ThemingInClassLib) doesn't work either.

**Comment by TWhidden** [comment]
It is for sure in its own library.  We can't use `StaticResource` because at the time of creation of the UserControl, those resources don't exist in a global resource directory. 

I totally agree on you with `StaticResource` vs `DynamicResource` - In this case though, I think it's just a style issue where when WPF goes to remeasure or something, it tries to do a divide by NaN.  The other MD styles don't have this that I can tell.

I do have it narrowed down to these Storyboard. If I remove these from the `UncheckedStoryboard`, the problem goes away.

```xaml
<DoubleAnimation Storyboard.TargetName="Thumb"
                 Storyboard.TargetProperty="Width"
                 To="{Binding Tag, ElementName=SwitchGrid}"
                 Duration="0" />
<DoubleAnimation Storyboard.TargetName="Thumb"
                 Storyboard.TargetProperty="Height"
                 To="{Binding Tag, ElementName=SwitchGrid}"
                 Duration="0" />
```

The Control appears to be working correctly without them those two `DoubleAnimation` values - I am not sure if they are needed, or how to fix just yet.

Are those Storyboards even needed for this control?

**Comment by nicolaihenriksen** [comment]
`DoubleAnimation.To` is not a `DependencyProperty`, and thus cannot be set via a binding (to my knowledge). I doubt these animations work/have ever worked. 

In a sample using `StaticResource` to reference the style, I would expect to see some errors/warnings in the output regarding these. Currently not at a computer, but I may have a look later...

In summary, it would surprise me if those animations do anything.

**Comment by nicolaihenriksen** [comment]
@TWhidden @corvinsz By playing around with the control, I believe the animations are actually in use, and they scale down the thumb when `ToggleButton.IsChecked=false` (which I guess is also fairly readable from the code). There are a number of sizes and animations at play here, so rather than trying to refactor the style, I opted to mitigate the issue by simply applying a fallback value to the binding. The fallback value should only come into play in the case where the control is being unloaded, because the `Tag` property will have a valid value when the control is visible/loaded.

**Comment by TWhidden** [comment]
@nicolaihenriksen  were you able to test with my reproduceable sample source above with that? I updated that style on my system here with the same fallbacks you put into that commit - but I still hit the same issue.

**Comment by TWhidden** [comment]
My setup is a mess here.  But if it wasn't working before and is working now - Im going to say is my own environment!  Ill pull your branch and re-test.

**Comment by nicolaihenriksen** [comment]
@TWhidden Let me know how it goes.

**Comment by corvinsz** [comment]
@nicolaihenriksen @TWhidden I did some quick testing and from what I can tell setting the `FallbackValue=0` doesn't fix the problem.
Here is the branch I was fiddling around with, if anyone is interested:
https://github.com/corvinsz/MaterialDesignInXamlToolkit/tree/fix3740

**Comment by TWhidden** [comment]
The problem still exists. I did find another solution, but will yield to you guys to let me know if this is an acceptable solution

If we apply a `From` value of `0`, that may provide a default value - It looks to have resolved my sample source, but unsure if that has any impact to the storyboard.  The `FallbackValue` I removed - didn't seem to make a difference either way.

```xaml
<DoubleAnimation Storyboard.TargetName="Thumb"
                 Storyboard.TargetProperty="Width"
                 From="0"
                 To="{Binding Tag, ElementName=SwitchGrid}"
                 Duration="0" />
<DoubleAnimation Storyboard.TargetName="Thumb"
                 Storyboard.TargetProperty="Height"
                 From="0"
                 To="{Binding Tag, ElementName=SwitchGrid}"
                 Duration="0"
                 />
```

I only am doing this on the `UncheckedStoryboard`.

**Comment by nicolaihenriksen** [comment]
@TWhidden @corvinsz You guys are right. But I was SURE I had seen it working so I had to figure out how I had seen that (to keep my sanity). 🤯 

It turns out, if you simply toggle the button on and off, the exception does not occur when you click the "ClickMe" button afterwards (at least not on my machine). And the fallback value therefore had nothing to do with the fact that I saw it working; I had simply toggled the button on/off before clicking the "ClickMe" button. I have closed the PR again.

I also had a quick test with `From="0"` as you mention, and that indeed seems to mitigate the problem. I couldn't really see any visual differences (tested without content and with custom content) so perhaps that is a viable fix 👍

**Comment by TWhidden** [comment]
Well, that style is for sure one of the coolest toggles, so if its committed, glad I can help!  That will be my second contribute! Did you want me to do a pull request on just those two lines?  This is one of my fav GitHub repos.

**Comment by nicolaihenriksen** [comment]
@TWhidden I think its appropriate that you do the PR and get the credit for it 👍 Personally I think the change is fine, but I think @Keboo - the maintainer - should have a look at it as well.

**Comment by corvinsz** [comment]
I'm closing this as #3776 merged
