### ISSUE TITLE
Transitioner ActivateFrame Problem

### ISSUE THREAD

**Issue by madfrog54321** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#421]
When I put the following in a xaml code, and then run the application:

`<materialDesign:Transitioner x:Name="PageHost" SelectedIndex="0">
        <materialDesign:TransitionerSlide OpeningEffect="{materialDesign:TransitionEffect None}">
            <Border Background="Green"/>
        </materialDesign:TransitionerSlide>
            <Border Background="Yellow"/>
    </materialDesign:Transitioner>`

I get the error: Object reference not set to an instance of an object.
The exception only happens when I change the selected index with: SelectedIndex="0"
I think the problem is with the GetSlide method in the transitioner.
When I change the xaml code to:

`<materialDesign:Transitioner x:Name="PageHost" SelectedIndex="0">
        <materialDesign:TransitionerSlide OpeningEffect="{materialDesign:TransitionEffect None}">
            <Border Background="Green"/>
        </materialDesign:TransitionerSlide>
        <materialDesign:TransitionerSlide OpeningEffect="{materialDesign:TransitionEffect None}">
            <Border Background="Yellow"/>
        </materialDesign:TransitionerSlide>
    </materialDesign:Transitioner>`

The exception is not thrown.

This transitioner is located inside another transitioner.
I have not gone through the entire code for the transitioner, so the nesting could be causing the problem.

I hope this information can help the community make the transitioner more reliable.

**Comment by ButchersBoy** [comment]
Hi, can you post the call stack?

**Comment by madfrog54321** [comment]
Here are the exception details:

System.NullReferenceException was unhandled
  HResult=-2147467261
  Message=Object reference not set to an instance of an object.
  Source=MaterialDesignThemes.Wpf
  StackTrace:
       at MaterialDesignThemes.Wpf.Transitions.Transitioner.ActivateFrame(Int32 selectedIndex, Int32 unselectedIndex)
       at MaterialDesignThemes.Wpf.Transitions.Transitioner.<.ctor>b__10_0(Object sender, RoutedEventArgs args)
       at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
       at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
       at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
       at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
       at System.Windows.BroadcastEventHelper.BroadcastEvent(DependencyObject root, RoutedEvent routedEvent)
       at System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(Object root)
       at MS.Internal.LoadedOrUnloadedOperation.DoWork()
       at System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()
       at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
       at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
       at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
       at System.Windows.Media.MediaContext.Resize(ICompositionTarget resizedCompositionTarget)
       at System.Windows.Interop.HwndTarget.OnResize()
       at System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
       at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
       at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
       at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
       at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
       at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
       at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
       at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
  InnerException:

**Comment by Keboo** [comment]
Fixed by #1242
