### ISSUE TITLE
TaskCanceledException in SnackbarMessageQueue when App.Current.Shutdown()

### ISSUE THREAD

**Issue by AmitBhatnagar24** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#608]
Get the following exception here: 

https://github.com/ButchersBoy/MaterialDesignInXamlToolkit/blob/master/MaterialDesignThemes.Wpf/SnackbarMessageQueue.cs#L275

when I shutdown my application via App.Current.Shutdown();

`{System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter1.GetResult()
   at MaterialDesignThemes.Wpf.SnackbarMessageQueue.<PumpAsync>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()}`

**Comment by ButchersBoy** [comment]
I can't easily reproduce this please provide a sample repo and instructions.

**Comment by Keboo** [comment]
I actually just hit this same issue (matching stack traces). I was running version 2.3.0.823. The error occurred when closing my app normally (clicked the X on the main window). 

One things that could be related. In my application, I am working with cameras. Inside my App.OnExit I stop any connected cameras. When the camera's stream is shut down it posts raises an event. Inside of this event handler I enqueue a message. 

I have compiled a custom build with additional logging and will let you know if I find more details.

**Comment by Keboo** [comment]
This issue is no longer possible as the background queue has been removed in the latest version
