### ISSUE TITLE
Unable to cast object of type 'MaterialDesignThemes.Wpf.Ripple' to type 'System.EventHandler'

### ISSUE THREAD

**Issue by tgiachi** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#805]
When I click on button, (random times) the application crash and show this error

Unable to cast object of type 'MaterialDesignThemes.Wpf.Ripple' to type 'System.EventHandler'

**Comment by ButchersBoy** [comment]
Call stack?

**Comment by tgiachi** [comment]
```
   at System.Windows.ContextLayoutManager.fireLayoutUpdateEvent()
   at System.Windows.ContextLayoutManager.UpdateLayout()
   at System.Windows.ContextLayoutManager.UpdateLayoutCallback(Object arg)
   at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by Keboo** [comment]
@tgiachi can you provide a sample project that reproduces the problem? I am unable to reproduce with the demo application.

**Comment by tgiachi** [comment]
It's happen random times, is possible to catch these errors?

**Comment by Keboo** [comment]
@tgiachi you can try having [VS break when the exception is first thrown](https://docs.microsoft.com/en-us/visualstudio/debugger/managing-exceptions-with-the-debugger). Also keep an eye on the InnerException property as sometimes you might only catch the exception after it has been wrapped.

I would also look at any areas around your buttons where you are doing things differently than what is in the demo project. Any special handling in code behind? Are you building any controls or manipulating the UI in C#? 
You might also look at other controls too. The ripple itself is used in several controls (button, calendar, popupbox, rating bar, etc). When you get this error is the button contained in a special control (listbox, datagrid, popup, etc)?

**Comment by wongjiahau** [comment]
@tgiachi I can't reproduce this error as well. You need to provide us a demo on how to reproduce the bug.

**Comment by Keboo** [comment]
Closing for now due to inactivity. If there is still an issue please re-open with details.
